### ISSUE TITLE
Histórico das tarefas #91

### ISSUE THREAD

**Issue by mineirim** [mineirim/observer#113]
Habilitar o histórico de tarefas
adicionar aba histórico de andamentos da tarefa ao lado do GANTT;

**Comment by mineirim** [comment]
histórico é exibido nos detalhes da tarefa

**Comment by IngridNascimento** [comment]
O histórico das tarefas não aparece. Quando "registro execução" e clico em salvar, o sistema não salva. Atualizei as telas o quanto pude e nada. Deve ter um problema na ferramenta salvar registro de execução. Testei as tarefas da atividade 1.3.1.1 (admin. como responsável).

**Comment by IngridNascimento** [comment]
Novo teste sem sucesso. Consigo ver a atualização do seu nome dentro da tela registrar execução, mas não vejo o histórico desse lançamento no espaço "detalhes" da tarefa. Ainda, não consigo salvar novo registro.

Observação: apenas as duas tarefas da atividade 1.3.1.1 tem o botao "registrar execução" disponível. Testei todas.

**Comment by IngridNascimento** [comment]
Funcionando.
