### ISSUE TITLE
Botão de Histórico das tarefas #91 

### ISSUE THREAD

**Issue by mineirim** [mineirim/observer#114]
adicionar botão para consulta de histórico na tela de execução da tarefa

**Comment by mineirim** [comment]
Exibido diretamente na tela de execução, sem clicar em botão

**Comment by IngridNascimento** [comment]
Não aparece registro. O que você chama de tela de execução da tarefa? O "registrar execução"; a caixa "edição" ou a coluna "execução" na imagem anexa? Creio que não há registro porque não consigo salvar inclusões de andamento na tela "registrar execução". Está interligado ao bug anterior que descrevi. 
![tela execucao da tarefa](https://cloud.githubusercontent.com/assets/8780964/6127032/9fd488e0-b10d-11e4-8b3e-9cb0381391d2.PNG)

**Comment by IngridNascimento** [comment]
Funcionando.
