### ISSUE TITLE
Dashboard - definir cores

### ISSUE THREAD

**Issue by IngridNascimento** [mineirim/observer#123]
Definir cores de fundo no dashboard conforme esquema de cores anexo. 

O que não será colorido: na tela de usuário Supervisor, os itens da coluna itens pendentes de aprovação (que podem ser "atividades" ou "tarefas") não serão coloridos por não haver necessidade de se definir um prazo para sua validação. 

Parâmetro para definição de cores:

Amarelo: quando a data atual representar mais de 80% do período entre a data de início e a data de encerramento.
Verde: quando a data atual representa menos de 80% do período entre a data de início e a data de encerramento.
Vermelho: quando a data atual é superior à data de encerramento.
Fundo branco: data atual anterior ao prazo de início da tarefa. 
Azul claro (pensar esse tom): encerrado dentro do prazo
Azul escuro (pensar esse tom): encerrado fora do prazo

**Comment by mineirim** [comment]
Por favor, poste as definições  conforme tabela de cores em hexadecimal ou RGB.

**Comment by IngridNascimento** [comment]
Seguem cores:

Yellow	#FFFF00	(255,255,0)
LimeGreen	#32CD32	(50,205,50)
FireBrick	#B22222	(178,34,34) [VERMELHO]
RoyalBlue	#4169E1	(65,105,225) [AZUL MAIS ESCURO]
DodgerBlue	#1E90FF	(30,144,255) [AZUL CLARO]

FONTE: http://erikasarti.net/html/tabela-cores/

**Comment by IngridNascimento** [comment]
Substituir a cor verde por essa:

#2ecc71   fonte: http://flatuicolors.com/

Substituir a cor vermelha por essa:
#FF6347

http://erikasarti.net/html/tabela-cores/
