### ISSUE TITLE
Substituição da ferramenta "botão direito" do menu contexto

### ISSUE THREAD

**Issue by IngridNascimento** [mineirim/observer#125]
Marcone, o Roberto pediu que aquela ideia de clicar com o botão direito sobre cada linha/nível para escolha de funcionalidade (relatório, anexos, editar etc) fosse retirada. Ele gostaria que essas opções estivessem incorporadas como botões dentro de cada caixa. É possível? O que acha? Me pareceu mais apropriado à visualização quando se refere a sistema. 

Att. 
Ingrid

**Comment by mineirim** [comment]
Serão adicionados botões à barra de tarefa, mas continua a opção pelo menu de contexto
