### ISSUE TITLE
Adicionar campos na tela de cadastro de projetos

### ISSUE THREAD

**Issue by IngridNascimento** [mineirim/observer#211]
Marcone: 
Para atender a demanda de sincronização, adicionar os seguintes campos à tela de projetos no SISPLAN:

ID do Projeto/Subprojeto
Meta do projeto
Incluir campo "objetivo"
Trocar "nome" por "título do projeto"

**Comment by mineirim** [comment]
ALTER TABLE projetos 
  ADD COLUMN  codigo character varying(50),
  ADD COLUMN  meta text,
  ADD COLUMN  objetivo text;
